### ISSUE TITLE
Adapt gz-sim-yarp-plugins to work with gz-sim8

### ISSUE THREAD

**Issue by xela-95** [robotology/gz-sim-yarp-plugins#58]
We want make the plugins of this repo to work with the latest stable release of Gazebo, i.e. [Gazebo Sim 8: Harmonic](https://github.com/gazebosim/gz-sim/releases/tag/gz-sim8_8.0.0)

### TODO

- [x] Update CMakeLists
- [x] Verify that all tests run successfully
- [x] Update readme with new version of gazebo package
- [x] Update CI yaml files

**Comment by xela-95** [comment]
I created a fresh new mamba environment with the following command:

```
mamba create -c conda-forge -n gz8 libgz-sim8 yarp cmake ninja pkg-config cmake compilers
```

When I activate this environment I get the following warning (at least I think):

```
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
- Make your system-wide implementation visible by installing ocl-icd-system conda package. 
```

@traversaro are you familiar with this?

**Comment by xela-95** [comment]
Unrelated to the previous message:

For my development setup I use additional packages, my mamba environment is in fact created as:

```
mamba create -c conda-forge -n gz8 libgz-sim8 yarp cmake ninja pkg-config cmake compilers clang clang-tools clang-format include-what-you-use 
```

Should I update the README with all those packages, or create separate environments.yaml for development and usage of the package?

**Comment by traversaro** [comment]
As gz-sim7 is part of Gazebo Garden (see https://gazebosim.org/docs/garden/install) and Gazebo Garden is a short-term support release of Gazebo (support will stop in November 2024, see https://gazebosim.org/docs/harmonic/releases), I think it is ok to just support gz-sim8 . In the future we may want to to support multiple version of gz-sim at the same time, but I see little value in trying to remain compatible with gz-sim7 at this stage.

**Comment by traversaro** [comment]
> Should I update the README with all those packages, or create separate environments.yaml for development and usage of the package?

Yes, I would separate the dependencies strictly required for the package usage, and the development dependencies. Anyhow, eventually we will add gz-sim-yarp-plugins will be added to conda-forge and to the robotology-superbuild, so the two main way of usage document in the README will be those one (see for example the idyntree README: https://github.com/robotology/idyntree?tab=readme-ov-file#installation) so eventually this will not be a big problem.

**Comment by traversaro** [comment]
> hen I activate this environment I get the following warning:
> 
> ```
> WARNING: No ICDs were found. Either,
> - Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
> - Make your system-wide implementation visible by installing ocl-icd-system conda package. 
> ```
> 
> @traversaro are you familiar with this?

Yes, see https://github.com/conda-forge/ocl-icd-feedstock/issues/29 .
